modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="ftbquestlocalizer"
version="3.2.0"
displayName="FTB Quests Localizer"
description='''
FTB Quests Localization Keys Converter
A Mod to export FTB Quest Files into Localization Files
'''
logoFile="logo.png"
credits="Bello,TheonlyTazz,Mrbysco,Horeak,YeraX7,ActiveRadar" #optional
authors="Litchiiiiiii"
[[dependencies.ftbquestlocalizer]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbquestlocalizer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"