modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="ftbquestlocalizer"
version="0.1.0"
displayName="FTB Quests Localizer"
description=''' FTB Quests Localization Keys Converter.\nA Mod to export FTB Quest Files into Localization Files. '''

[[dependencies.ftbconv]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbconv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"