modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
credits="Bello,TheonlyTazz,Mrbysco,Horeak,YeraX7,ActiveRadar" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
logoFile = "assets/ftbquestlocalizer/textures/logo.png"
[[dependencies.ftbquestlocalizer]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ftbquestlocalizer]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

